#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef INDOORSCORESDK_SWIFT_H
#define INDOORSCORESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#import <IndoorsCoreSDK/IndoorsCoreSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="IndoorsCoreSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class NSNumber;
@class UIImage;

SWIFT_CLASS("_TtC14IndoorsCoreSDK13INTagMapModel")
@interface INTagMapModel : NSObject <INTrackedMapObject>
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, strong) NSNumber * _Nullable x;
@property (nonatomic, readonly, strong) NSNumber * _Nullable y;
@property (nonatomic, readonly, strong) NSNumber * _Nullable floor;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, strong) NSNumber * _Nonnull isActive;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) NSNumber * _Nonnull unixTimestamp;
@property (nonatomic, copy) NSString * _Nullable tagName;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable objectDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, INTagModelName, open) {
  INTagModelNamePnevent = 0,
  INTagModelNameAoaTagLocation = 1,
  INTagModelNameUwbTagLocation = 2,
  INTagModelNameBleTagLocation = 3,
  INTagModelNameLaserLocation = 4,
  INTagModelNameTrackpoint = 5,
  INTagModelNameUndefinedDevice = 6,
};

@class INCoreConfiguration;
@class INAuthService;
@class INAppDatabase;
@class INReachability;
@class INBuilding;

SWIFT_CLASS("_TtC14IndoorsCoreSDK12INTagService")
@interface INTagService : NSObject
- (nonnull instancetype)initWithConfiguration:(INCoreConfiguration * _Nonnull)configuration authService:(INAuthService * _Nonnull)authService database:(INAppDatabase * _Nonnull)database reachability:(INReachability * _Nonnull)reachability building:(INBuilding * _Nullable)building OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK25INTrackingWebSocketObject_")
@protocol INTrackingWebSocketObject <INTrackedMapObject>
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, readonly) NSInteger timestamp;
@end


SWIFT_CLASS("_TtC14IndoorsCoreSDK22INTrackedSocketPNEvent")
@interface INTrackedSocketPNEvent : NSObject <INTrackingWebSocketObject>
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, readonly) NSInteger id;
@property (nonatomic, readonly) NSInteger createdAt;
@property (nonatomic, readonly) NSInteger updatedAt;
@property (nonatomic, readonly) NSInteger deleted;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, readonly, strong) NSNumber * _Nullable x;
@property (nonatomic, readonly, strong) NSNumber * _Nullable y;
@property (nonatomic, readonly) NSInteger timestamp;
@property (nonatomic, readonly) NSInteger processed;
@property (nonatomic, readonly) NSInteger application;
@property (nonatomic, readonly, copy) NSString * _Nullable editor;
@property (nonatomic, readonly, strong) NSNumber * _Nullable tagZone;
@property (nonatomic, readonly, strong) NSNumber * _Nullable floor;
@property (nonatomic, readonly, strong) NSNumber * _Nullable tag;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, strong) NSNumber * _Nonnull isActive;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) NSNumber * _Nonnull unixTimestamp;
@property (nonatomic, copy) NSString * _Nullable tagName;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable objectDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14IndoorsCoreSDK25INTrackedSocketTrackpoint")
@interface INTrackedSocketTrackpoint : NSObject <INTrackingWebSocketObject>
@property (nonatomic, readonly, copy) NSString * _Nullable device;
@property (nonatomic, readonly, copy) NSString * _Nullable user;
@property (nonatomic, readonly, copy) NSString * _Nonnull uuid;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, strong) NSNumber * _Nullable floor;
@property (nonatomic, readonly, strong) NSNumber * _Nullable x;
@property (nonatomic, readonly, strong) NSNumber * _Nullable y;
@property (nonatomic, strong) NSNumber * _Nonnull isActive;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) NSNumber * _Nonnull unixTimestamp;
@property (nonatomic, copy) NSString * _Nullable tagName;
@property (nonatomic, copy) NSString * _Nullable company;
@property (nonatomic, copy) NSString * _Nullable email;
@property (nonatomic, copy) NSString * _Nullable objectDescription;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic) NSInteger timestamp;
@property (nonatomic, readonly, strong) NSNumber * _Nullable clientTimestamp;
@property (nonatomic, readonly, strong) NSNumber * _Nullable serverTimestamp;
@property (nonatomic, readonly, strong) NSNumber * _Nullable deviceModel;
@property (nonatomic, readonly, strong) NSNumber * _Nullable deviceVendor;
@property (nonatomic, readonly, strong) NSNumber * _Nullable zoneChanged;
@property (nonatomic, readonly, strong) NSNumber * _Nullable source;
@property (nonatomic, readonly, strong) NSNumber * _Nullable zoneId;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK36INTrackingListObjectsManagerDelegate_")
@protocol INTrackingListObjectsManagerDelegate
/// A function for handling tracking object updates
- (void)trackingObjectsManagerDidUpdateWithObject:(id <INTrackedMapObject> _Nonnull)object;
/// A function for handling the addition of a tracking object
- (void)trackingObjectsManagerDidAddWithObject:(id <INTrackedMapObject> _Nonnull)object andType:(enum INTagModelName)type;
/// A function for handling the deletion of a tracking object
- (void)trackingObjectsManagerDidDeleteWithObject:(id <INTrackedMapObject> _Nonnull)object;
@end


SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK22INTrackingMapViewInput_")
@protocol INTrackingMapViewInput
- (void)show3DMapWith:(NSArray<INBuilding *> * _Nonnull)buildings andFocusedBuilding:(INBuilding * _Nonnull)building;
- (void)restartMapBuildingNavigation;
- (void)setCurrentBuilding:(INBuilding * _Nonnull)building;
@end


/// A delegate of a manager that handle received tracked objects
SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK32INTrackingObjectsManagerDelegate_")
@protocol INTrackingObjectsManagerDelegate
/// Check floor. Needs for handling objects for only current floor
- (BOOL)isCurrentFloorWithFloorId:(NSNumber * _Nullable)floorId SWIFT_WARN_UNUSED_RESULT;
/// A function for handling tracking object updates
- (void)trackingObjectsManagerDidUpdateWithObject:(id <INTrackedMapObject> _Nonnull)object;
/// A function for handling the addition of a tracking object
- (void)trackingObjectsManagerDidAddWithObject:(id <INTrackedMapObject> _Nonnull)object;
/// A function for handling the addition of a tracking object for another floor
- (void)trackingObjectsManagerDidAddForAnotherFloorWithObject:(id <INTrackedMapObject> _Nonnull)object;
/// A function for handling the deletion of a tracking object
- (void)trackingObjectsManagerDidDeleteWithObject:(id <INTrackedMapObject> _Nonnull)object;
@end

@class NSDictionary;

/// A delegate that gets changes of tracked objects
SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK26INTrackingObserverDelegate_")
@protocol INTrackingObserverDelegate
@property (nonatomic, strong) id <INTrackingObjectsManagerDelegate> _Nullable delegate;
@property (nonatomic, strong) id <INTrackingListObjectsManagerDelegate> _Nullable listDelegate;
/// A function that handle the gotten objects of tracking from socket
- (void)trackingObserverGetWithObject:(id <INTrackingWebSocketObject> _Nonnull)object with:(enum INTagModelName)tagModelName;
/// Processes the received tracking object and calls the necessary function from the delegate, depending on its object parameters.
/// \param apiObjects <code>[INTrackedMapObject]</code> all objects from api
///
/// \param tagModels <code>[String: INTagModelName]</code>a key in dictionary is the UUID of object.
///
- (void)trackingObserverGetWithApiObjects:(NSArray<id <INTrackedMapObject>> * _Nonnull)apiObjects tagModels:(NSDictionary * _Nonnull)tagModels;
/// Set value for dictionary with tags types, need for correct handling of changing setting state
/// \param tagsTypes <code>[String: INTagModelName]</code>a key in dictionary is the UUID of object.
///
- (void)setTagsTypes:(NSDictionary * _Nullable)tagsTypes;
/// Need for adding or deleting elements after settings changing
- (void)handleFloorChanging:(NSInteger)floorId;
/// Change image for web socket object on map
- (void)redrawObject:(id <INTrackingWebSocketObject> _Nonnull)object;
- (BOOL)objectHasImageWithObject:(id <INTrackedMapObject> _Nonnull)object SWIFT_WARN_UNUSED_RESULT;
/// Turn on the timer that call delete function for live tracking objects
- (void)startObjectObsolescenceTimer;
/// Turn off the timer that call delete function for live tracking objects
- (void)stopObjectObsolescenceTimer;
@end


SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK32INTrackingScreenDelegateProtocol_")
@protocol INTrackingScreenDelegateProtocol
- (void)disconnectSocket;
- (void)connectSocket;
@end


SWIFT_CLASS("_TtC14IndoorsCoreSDK17INTrackingService")
@interface INTrackingService : NSObject
- (nonnull instancetype)initWithConfiguration:(INCoreConfiguration * _Nonnull)configuration authService:(INAuthService * _Nonnull)authService database:(INAppDatabase * _Nonnull)database reachability:(INReachability * _Nonnull)reachability OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface INTrackingService (SWIFT_EXTENSION(IndoorsCoreSDK)) <INTrackingScreenDelegateProtocol>
- (void)connectSocket;
- (void)disconnectSocket;
@end


/// Delegates the handling of the received messages
SWIFT_PROTOCOL("_TtP14IndoorsCoreSDK25INTrackingServiceDelegate_")
@protocol INTrackingServiceDelegate
@end

typedef SWIFT_ENUM(NSInteger, INTrackingSettingType, open) {
  INTrackingSettingTypeAllObjects = 0,
  INTrackingSettingTypeUsers = 1,
  INTrackingSettingTypeUndefinedDevices = 2,
  INTrackingSettingTypeTagBLE = 3,
  INTrackingSettingTypeTagAoA = 4,
  INTrackingSettingTypeTagUWB = 5,
  INTrackingSettingTypeVideoObjects = 6,
  INTrackingSettingTypeLidarObjects = 7,
  INTrackingSettingTypePc = 8,
  INTrackingSettingTypeGlobalNotifications = 9,
  INTrackingSettingTypeShowNotificationsForAllUsers = 10,
  INTrackingSettingTypeShowNoActiveDevices = 11,
  INTrackingSettingTypeShowOtherFloorsDevices = 12,
};


SWIFT_CLASS("_TtC14IndoorsCoreSDK25INTrackingSettingsManager")
@interface INTrackingSettingsManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14IndoorsCoreSDK29INTrackingWSTrackpointMessage")
@interface INTrackingWSTrackpointMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull appLabel;
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
@property (nonatomic, readonly, copy) NSString * _Nonnull method;
@property (nonatomic, readonly, strong) INTrackedSocketTrackpoint * _Nonnull trackedObject;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC14IndoorsCoreSDK26INTrackingWebSocketMessage")
@interface INTrackingWebSocketMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull appLabel;
@property (nonatomic, readonly, copy) NSString * _Nonnull modelName;
@property (nonatomic, readonly, copy) NSString * _Nonnull method;
@property (nonatomic, readonly, strong) INTrackedSocketPNEvent * _Nonnull trackedObject;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC14IndoorsCoreSDK14INUsersService")
@interface INUsersService : NSObject
- (nonnull instancetype)initWithConfiguration:(INCoreConfiguration * _Nonnull)configuration authService:(INAuthService * _Nonnull)authService database:(INAppDatabase * _Nonnull)database reachability:(INReachability * _Nonnull)reachability building:(INBuilding * _Nonnull)building OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
